### ISSUE TITLE
Mark

### ISSUE THREAD

**Issue by mtugnoli** [StefanOssendorf/BulkMailing#1]
Sorry I don't using GitHub,

Here some suggest :

1) Is possible to use also in WinForm ?
2) It will be good to have event (with msg is) when sent/error 
3) to prevent server overflow, it will be great to send with many stmp servers
4) now I try to use it, but is difficult debug task
5) a logging function is always good.

Thank You for attention

**Comment by StefanOssendorf** [comment]
Hi, no Problem :) It's easier and if other people comes around maybe it is helpful for them, too!

Here my answers:
@1 Yes, this library is designed to be used in winforms as well as in windows services (It's targeting framework 4.5)

@2 Maybe these samples are helpful: https://github.com/StefanOssendorf/BulkMailing/blob/master/samples/SendSingleMail/Program.cs
The intention of this lib is to send e-mails in a non blocking way. So you can consume the MailStreamResult.Result to iterate over all already sent mails and get the status of the mail (sent/canceled/error).

@3 You mean e.g. sending over two (or more) different smpt servers? If yes, this scenario is not supported.

@4 Here are some smples of usage: https://github.com/StefanOssendorf/BulkMailing/blob/master/samples/SendSingleMail/Program.cs I hope this helps.

@5 Logging of what exactly? In general I agree, but my library should not throw any exception (except preconditions) and you have access to all exception through either the MailStreamResult or the MailSendResult.

I hope I could answer your questions.

Cheers Stefan
